/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packageVista;

/**
 *
 * @author Maria Jose
 */
public class VistaProcesador extends javax.swing.JFrame {

    /**
     * Creates new form VistaProcesador
     */
    public VistaProcesador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        validardtd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDTD = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoDTD = new javax.swing.JTextArea();
        cargarXML1 = new javax.swing.JButton();
        cargarDTD = new javax.swing.JButton();
        validarDTD = new javax.swing.JButton();
        guardarDTD = new javax.swing.JButton();
        limpiarDTD = new javax.swing.JButton();
        validarxsd = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaXML2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaXSD = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        resultadoXSD = new javax.swing.JTextArea();
        cargarXML2 = new javax.swing.JButton();
        cargarXSD = new javax.swing.JButton();
        validarXSD = new javax.swing.JButton();
        guardarXSD = new javax.swing.JButton();
        limpiarXSD = new javax.swing.JButton();
        validarxpath = new javax.swing.JPanel();
        jTextFieldXPATH = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaXML3 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        resultadoXPATH = new javax.swing.JTextArea();
        cargarXML3 = new javax.swing.JButton();
        evaluarXPATH = new javax.swing.JButton();
        limpiarXPATH = new javax.swing.JButton();
        validarxslt = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaXML4 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaXSLT = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        resultadoXSLT = new javax.swing.JTextArea();
        cargarXML4 = new javax.swing.JButton();
        guardarXML = new javax.swing.JButton();
        cargarXSLT = new javax.swing.JButton();
        guardarXSLT = new javax.swing.JButton();
        HTMLsalida = new javax.swing.JButton();
        ejecutarXSLT = new javax.swing.JButton();
        about = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaDTD.setColumns(20);
        jTextAreaDTD.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDTD);

        resultadoDTD.setColumns(20);
        resultadoDTD.setRows(5);
        jScrollPane2.setViewportView(resultadoDTD);

        cargarXML1.setText("Cargar XML");

        cargarDTD.setText("Cargar DTD");

        validarDTD.setText("Validar");

        guardarDTD.setText("Guardar");

        limpiarDTD.setText("Limpiar");

        javax.swing.GroupLayout validardtdLayout = new javax.swing.GroupLayout(validardtd);
        validardtd.setLayout(validardtdLayout);
        validardtdLayout.setHorizontalGroup(
            validardtdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validardtdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(validardtdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cargarXML1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cargarDTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limpiarDTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarDTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(validarDTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135)
                .addGroup(validardtdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        validardtdLayout.setVerticalGroup(
            validardtdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validardtdLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(validardtdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(validardtdLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(validardtdLayout.createSequentialGroup()
                        .addComponent(cargarXML1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cargarDTD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(validarDTD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guardarDTD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpiarDTD)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Validar DTD", validardtd);

        jTextAreaXML2.setColumns(20);
        jTextAreaXML2.setRows(5);
        jScrollPane3.setViewportView(jTextAreaXML2);

        jTextAreaXSD.setColumns(20);
        jTextAreaXSD.setRows(5);
        jScrollPane4.setViewportView(jTextAreaXSD);

        resultadoXSD.setColumns(20);
        resultadoXSD.setRows(5);
        jScrollPane5.setViewportView(resultadoXSD);

        cargarXML2.setText("Cargar XML");

        cargarXSD.setText("Cargar XSD");

        validarXSD.setText("Validar");

        guardarXSD.setText("Guardar");

        limpiarXSD.setText("Limpiar");

        javax.swing.GroupLayout validarxsdLayout = new javax.swing.GroupLayout(validarxsd);
        validarxsd.setLayout(validarxsdLayout);
        validarxsdLayout.setHorizontalGroup(
            validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validarxsdLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(validarxsdLayout.createSequentialGroup()
                        .addGroup(validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(validarXSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardarXSD, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(limpiarXSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(validarxsdLayout.createSequentialGroup()
                        .addGroup(validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargarXML2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addGroup(validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargarXSD)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        validarxsdLayout.setVerticalGroup(
            validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validarxsdLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarXML2)
                    .addComponent(cargarXSD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(validarxsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(validarxsdLayout.createSequentialGroup()
                        .addComponent(validarXSD)
                        .addGap(18, 18, 18)
                        .addComponent(guardarXSD)
                        .addGap(18, 18, 18)
                        .addComponent(limpiarXSD))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Validad XSD", validarxsd);

        jTextAreaXML3.setColumns(20);
        jTextAreaXML3.setRows(5);
        jScrollPane6.setViewportView(jTextAreaXML3);

        resultadoXPATH.setColumns(20);
        resultadoXPATH.setRows(5);
        jScrollPane7.setViewportView(resultadoXPATH);

        cargarXML3.setText("Cargar XML");

        evaluarXPATH.setText("Evaluar XPath");

        limpiarXPATH.setText("Limpiar XPath");

        javax.swing.GroupLayout validarxpathLayout = new javax.swing.GroupLayout(validarxpath);
        validarxpath.setLayout(validarxpathLayout);
        validarxpathLayout.setHorizontalGroup(
            validarxpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validarxpathLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(validarxpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(evaluarXPATH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limpiarXPATH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cargarXML3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84)
                .addGroup(validarxpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldXPATH)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        validarxpathLayout.setVerticalGroup(
            validarxpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validarxpathLayout.createSequentialGroup()
                .addGroup(validarxpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(validarxpathLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldXPATH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(validarxpathLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(cargarXML3)
                        .addGap(48, 48, 48)
                        .addComponent(evaluarXPATH)
                        .addGap(51, 51, 51)
                        .addComponent(limpiarXPATH)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Validar XPath", validarxpath);

        jTextAreaXML4.setColumns(20);
        jTextAreaXML4.setRows(5);
        jScrollPane8.setViewportView(jTextAreaXML4);

        jTextAreaXSLT.setColumns(20);
        jTextAreaXSLT.setRows(5);
        jScrollPane9.setViewportView(jTextAreaXSLT);

        resultadoXSLT.setColumns(20);
        resultadoXSLT.setRows(5);
        jScrollPane10.setViewportView(resultadoXSLT);

        cargarXML4.setText("Cargar XML");

        guardarXML.setText("Cargar XSLT");

        cargarXSLT.setText("Guardar XML");

        guardarXSLT.setText("Guardar XSLT");

        HTMLsalida.setText("HTML Salida");

        ejecutarXSLT.setText("Ejecutar");

        javax.swing.GroupLayout validarxsltLayout = new javax.swing.GroupLayout(validarxslt);
        validarxslt.setLayout(validarxsltLayout);
        validarxsltLayout.setHorizontalGroup(
            validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validarxsltLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(validarxsltLayout.createSequentialGroup()
                        .addGroup(validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(validarxsltLayout.createSequentialGroup()
                                .addComponent(cargarXML4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cargarXSLT))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(validarxsltLayout.createSequentialGroup()
                                .addComponent(guardarXML)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(guardarXSLT))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(validarxsltLayout.createSequentialGroup()
                        .addGroup(validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HTMLsalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ejecutarXSLT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        validarxsltLayout.setVerticalGroup(
            validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validarxsltLayout.createSequentialGroup()
                .addGroup(validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(validarxsltLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarXML)
                            .addComponent(guardarXSLT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(validarxsltLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargarXML4)
                            .addComponent(cargarXSLT))
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(validarxsltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(validarxsltLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(HTMLsalida)
                        .addGap(18, 18, 18)
                        .addComponent(ejecutarXSLT)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Validar XSLT", validarxslt);

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about);
        about.setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About", about);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Validar DTD");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProcesador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProcesador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HTMLsalida;
    private javax.swing.JPanel about;
    private javax.swing.JButton cargarDTD;
    private javax.swing.JButton cargarXML1;
    private javax.swing.JButton cargarXML2;
    private javax.swing.JButton cargarXML3;
    private javax.swing.JButton cargarXML4;
    private javax.swing.JButton cargarXSD;
    private javax.swing.JButton cargarXSLT;
    private javax.swing.JButton ejecutarXSLT;
    private javax.swing.JButton evaluarXPATH;
    private javax.swing.JButton guardarDTD;
    private javax.swing.JButton guardarXML;
    private javax.swing.JButton guardarXSD;
    private javax.swing.JButton guardarXSLT;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaDTD;
    private javax.swing.JTextArea jTextAreaXML2;
    private javax.swing.JTextArea jTextAreaXML3;
    private javax.swing.JTextArea jTextAreaXML4;
    private javax.swing.JTextArea jTextAreaXSD;
    private javax.swing.JTextArea jTextAreaXSLT;
    private javax.swing.JTextField jTextFieldXPATH;
    private javax.swing.JButton limpiarDTD;
    private javax.swing.JButton limpiarXPATH;
    private javax.swing.JButton limpiarXSD;
    private javax.swing.JTextArea resultadoDTD;
    private javax.swing.JTextArea resultadoXPATH;
    private javax.swing.JTextArea resultadoXSD;
    private javax.swing.JTextArea resultadoXSLT;
    private javax.swing.JButton validarDTD;
    private javax.swing.JButton validarXSD;
    private javax.swing.JPanel validardtd;
    private javax.swing.JPanel validarxpath;
    private javax.swing.JPanel validarxsd;
    private javax.swing.JPanel validarxslt;
    // End of variables declaration//GEN-END:variables
}
